name: Dart CI

on:
  push:
    paths:
    - 'lib/**'
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run:  flutter pub get
    - name: Run tests
      run: flutter run test
