name: Flutter CI

on:
  push:
    paths:
    - 'lib/**'
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - uses: subosito/flutter-action@v1
      with:
       flutter-version: 'v1.12.13+hotfix.9'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
